# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_time', models.TimeField(default=datetime.time(10, 0), verbose_name='class time')),
                ('class_dayOfTheWeek', models.IntegerField()),
                ('class_level', models.CharField(max_length=20)),
                ('class_lacation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank_id', models.IntegerField()),
                ('gain_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('ins_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ins_name', models.CharField(max_length=20)),
                ('ins_birth_date', models.DateField(default=datetime.date(1980, 1, 1), verbose_name='instructor birthday')),
                ('ins_phone', models.CharField(max_length=30)),
                ('ins_email', models.EmailField(max_length=254)),
                ('ins_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inv_date', models.DateField(default=datetime.date.today)),
                ('inv_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meeting_date', models.DateField(default=datetime.date.today)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('par_id', models.IntegerField(primary_key=True, serialize=False)),
                ('par_phone', models.CharField(max_length=30)),
                ('par_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('pur_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pur_item_name', models.CharField(max_length=30)),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank_name', models.CharField(max_length=20)),
                ('rank_belt_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('req_id', models.IntegerField(primary_key=True, serialize=False)),
                ('req_info', models.CharField(max_length=100)),
                ('rank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_fname', models.CharField(max_length=100)),
                ('stu_lname', models.CharField(max_length=100)),
                ('stu_birth_date', models.DateField(default=datetime.date(1990, 1, 1), verbose_name='birthday')),
                ('stu_join_date', models.DateField(default=datetime.date.today, verbose_name='join date')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_fname', models.CharField(max_length=100)),
                ('stu_lname', models.CharField(max_length=100)),
                ('stu_birth_date', models.DateField(default=datetime.date(1990, 1, 1), verbose_name='birthday')),
                ('stu_join_date', models.DateField(default=datetime.date.today, verbose_name='join date')),
                ('stu_phone', models.CharField(max_length=30, null=True)),
                ('stu_email', models.EmailField(max_length=254, null=True)),
                ('stu_address', models.CharField(max_length=100, null=True)),
                ('ins_id', models.ForeignKey(default=2001, on_delete=django.db.models.deletion.CASCADE, to='TestModel.Instructor')),
                ('meeting_id', models.ForeignKey(default=3001, on_delete=django.db.models.deletion.CASCADE, to='TestModel.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='gain',
            unique_together=set([('stu_id', 'rank_id')]),
        ),
        migrations.AddField(
            model_name='class',
            name='ins_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Instructor'),
        ),
    ]
