# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20170310_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_lacation',
            new_name='class_location',
        ),
    ]
