# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20170310_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Students'),
        ),
    ]
