# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-11 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20170310_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gain',
        ),
    ]
