# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0009_auto_20170321_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='ins_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inv_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='par_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='pur_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
