# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0010_auto_20170322_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='meeting_id',
            field=models.ForeignKey(default=4001, on_delete=django.db.models.deletion.CASCADE, to='TestModel.Meeting'),
        ),
    ]
