# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0011_auto_20170322_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_dayOfTheWeek',
            field=models.CharField(max_length=20),
        ),
    ]
